### ISSUE TITLE
invoke-msbuild  -Path "c:\path\to\sln.sln" on PS 6.0.0.17 warns : cannot find parameter "WindowsStyle"

### ISSUE THREAD

**Issue by jmp75** [deadlydog/Invoke-MsBuild#22]
using "C:\Program Files\PowerShell\6.0.0.17\powershell.exe"

Invoke-MsBuild : Unexpected error occurred while building "C:\src\github_jm\moirai\tests\moirai_test.sln": A parameter cannot be found that matches parameter name 'WindowStyle'.

I'll see if I can fork and fix - I am new to PS...

**Comment by deadlydog** [comment]
From the version number `6.0.0.17` I'm guessing that you're using PowerShell Core, which I believe is designed to be multi-platform. My *guess* is that version of PowerShell makes a breaking change to no longer use (or fully support) System.Diagnostics.Process, which is what Invoke-MsBuild uses to launch the MsBuild.exe process along with the `WindowStyle` parameter for it.

If you flip to using PowerShell v5 or less you should not have this problem. Because PowerShell Core is still in development and hasn't even released a RC version, I won't be trying to update the script to make it v6 compatible yet.
