### ISSUE TITLE
.net Core 2.2?

### ISSUE THREAD

**Issue by mwoffenden** [deadlydog/Invoke-MsBuild#44]
Does Invoke-MsBuild work for .net Core 2.2?

**Comment by deadlydog** [comment]
Hmmm, I'm not certain if msbuild.exe can build .Net Core projects......I haven't tried yet. Typically you build .Net Core projects using [the dotnet.exe](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build), which gets included in your PATH by default and should be available on the command line.

When I have a moment I'll test out building .Net Core with msbuild.

**Comment by mwoffenden** [comment]
So it sounds to me like there's no "invoke-msbuild" for .net core, is that correct?

**Comment by deadlydog** [comment]
Hmmm, I just tried using `Invoke-MsBuild` to build a .sln with .Net Core 2.0 projects in it and it succeeded, so I guess it can be used for .Net Core :)

**Comment by mwoffenden** [comment]
Excellent, I'll give it a try!

**Comment by deadlydog** [comment]
So I just did some experimenting and it is able to build .Net Core 2.2 projects and solutions fine, as long as you remember to first do a NuGet package restore (e.g. `dotnet restore`) so that the assemblies it needs for the build are available. With that, I'm going to close this one off.

**Comment by deadlydog** [comment]
I also just [found this](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore):
> MSBuild: use the msbuild -t:restore command, which restores packages packages listed in the project file (PackageReference only). Available only in NuGet 4.x+ and MSBuild 15.1+, which are included with Visual Studio 2017. nuget restore and dotnet restore both use this command for applicable projects.

So for Invoke-MsBuild and .Net Core projects, that means you can do this:

```
Invoke-MsBuild .\ConsoleApp1.sln -MsBuildParameters "-t:restore"
```

And it will restore packages and build successfully :-)

**Comment by mwoffenden** [comment]
Will try that too.  Previously I was restoring in a separate step.

**Comment by mwoffenden** [comment]
So I'm trying Invoke-MsBuild on a .NET core project from the ISE.  It appears to be running but I cannot tell, it might also just be hung up.  

Is there a "verbose" mode that I could use to spy on it?

**Comment by deadlydog** [comment]
Hmmm, I _assume_ if you have any version of Visual Studio installed it will also have `NuGet` and `dotnet.exe` installed already, but for DotNet Core apps I assume you need _at least_ Visual Studio 2017 installed. I don't think you need Visual Studio 2019 installed to build .Net Core 2.2 apps, but you likely would need to have the [DotNet Core 2.2+ SDK](https://dotnet.microsoft.com/download) installed.

I know it has been a common ask in the past to be able to setup a build server without installing Visual Studio on it and only install MSBuild, but last time I checked (a couple years ago) nobody was able to get it to work reliably, and from the forums / issues I read most people just ended up installing Visual Studio on the build servers. That was for .Net Framework apps though, not DotNet Core though, so that may not be the case for DotNet Core apps.
